-- MySQL Script generated by MySQL Workbench
-- Wed Jan  3 08:04:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户id',
  `password` VARCHAR(25) NULL COMMENT '密码',
  `nickname` VARCHAR(12) NULL COMMENT '昵称',
  `true_name` VARCHAR(12) NULL COMMENT '真实姓名',
  `gender` VARCHAR(2) NULL COMMENT '性别',
  `email` VARCHAR(45) NULL COMMENT '邮箱',
  `head_url` VARCHAR(200) NULL COMMENT '头像路径',
  `bg_url` VARCHAR(200) NULL COMMENT '主页背景图片路径',
  `introduce` VARCHAR(500) NULL COMMENT '个人简介\n',
  `regist_date` TIMESTAMP NULL COMMENT '注册日期',
  `is_admin` INT NULL COMMENT '是否为admin',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article` (
  `article_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '文章表的ID',
  `user_id` INT UNSIGNED NOT NULL COMMENT '文章作者的用户名',
  `title` VARCHAR(50) NULL COMMENT '文章的标题',
  `create_time` TIMESTAMP NULL COMMENT '文章创建日期',
  `update_time` TIMESTAMP NULL COMMENT '最近更新时间',
  `article_sum` TEXT(200) NULL COMMENT '文章简介\n',
  `type_id` INT NULL COMMENT '类型',
  `views` INT NULL COMMENT '浏览量',
  `comments` INT NULL COMMENT '评论数',
  `collections` INT NULL COMMENT '收藏数',
  `content_url` TEXT(300) NULL COMMENT '文章url',
  `title_image_url` TEXT(300) NULL COMMENT '题图url',
  `ban` TINYINT NULL COMMENT '表示文章是否该被封禁',
  PRIMARY KEY (`article_id`),
  INDEX `fk_user_article_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_article_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`article_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article_comment` (
  `article_comment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '评论编号',
  `article_id` INT UNSIGNED NULL COMMENT '文章的ID',
  `discusser` VARCHAR(25) NULL COMMENT '发出评论的用户名',
  `text` TEXT(500) NULL COMMENT '评论正文500字',
  `create_time` TIMESTAMP NULL COMMENT '评论的创建时间',
  PRIMARY KEY (`article_comment_id`),
  INDEX `fk_comment_user_article1_idx` (`article_id` ASC),
  CONSTRAINT `fk_comment_user_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `mydb`.`article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`article_reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article_reply` (
  `article_reply_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '	回复的编号',
  `article_comment_id` INT UNSIGNED NULL COMMENT '	评论的编号',
  `replier` INT NULL COMMENT '发出回复的用户',
  `user_id` INT NULL COMMENT '被回复的用户',
  `re_time` TIMESTAMP NULL COMMENT '回复时间',
  `text` TEXT(500) NULL COMMENT '回复内容500字',
  PRIMARY KEY (`article_reply_id`),
  INDEX `fk_reply_comment1_idx` (`article_comment_id` ASC),
  CONSTRAINT `fk_reply_comment1`
    FOREIGN KEY (`article_comment_id`)
    REFERENCES `mydb`.`article_comment` (`article_comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attention` (
  `attention_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '关注表的编号',
  `follower` INT UNSIGNED NULL COMMENT '发出关注的用户名（id）',
  `user_id` INT UNSIGNED NULL COMMENT '被关注的用户名（id）',
  PRIMARY KEY (`attention_id`),
  INDEX `fk_attention_user1_idx` (`follower` ASC),
  INDEX `fk_attention_user2_idx` (`user_id` ASC),
  CONSTRAINT `fk_attention_user1`
    FOREIGN KEY (`follower`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attention_user2`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_category` (
  `course_category_id` INT NOT NULL AUTO_INCREMENT COMMENT '一级列表ID(主键)',
  `title` VARCHAR(45) NULL COMMENT '标题',
  `seq` VARCHAR(45) NULL COMMENT '序号',
  PRIMARY KEY (`course_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_detail_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_detail_category` (
  `course_detail_category_id` INT NOT NULL AUTO_INCREMENT COMMENT '二级列表ID(主键)',
  `course_category_id` INT NOT NULL COMMENT '对应一级列表ID',
  `title` VARCHAR(45) NULL COMMENT '标题',
  `seq` INT NULL COMMENT '序号',
  PRIMARY KEY (`course_detail_category_id`),
  INDEX `fk_school_listlv2_school_listlv11_idx` (`course_category_id` ASC),
  CONSTRAINT `fk_school_listlv2_school_listlv11`
    FOREIGN KEY (`course_category_id`)
    REFERENCES `mydb`.`course_category` (`course_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_collection` (
  `course_collection_id` INT NOT NULL COMMENT '教程集合ID(主键)',
  `course_detail_category_id` INT NOT NULL COMMENT '对应二级列表ID',
  `title` VARCHAR(45) NULL COMMENT '标题',
  `seq` VARCHAR(45) NULL COMMENT '序号',
  `summary` VARCHAR(50) NULL COMMENT '摘要',
  PRIMARY KEY (`course_collection_id`),
  INDEX `fk_school_listlv3_school_listlv21_idx` (`course_detail_category_id` ASC),
  CONSTRAINT `fk_school_listlv3_school_listlv21`
    FOREIGN KEY (`course_detail_category_id`)
    REFERENCES `mydb`.`course_detail_category` (`course_detail_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_info` (
  `course_id` INT UNSIGNED NOT NULL COMMENT '教程ID(主键)',
  `title` VARCHAR(45) NULL COMMENT '标题',
  `seq` INT NULL COMMENT '序号',
  `author_id` INT UNSIGNED NOT NULL COMMENT '作者',
  `source` VARCHAR(45) NULL COMMENT '来源',
  `createdate` TIMESTAMP NULL COMMENT '创建日期',
  `update_time` TIMESTAMP NULL COMMENT '最后更新日期',
  `comments` INT NULL COMMENT '评论数',
  `views` INT NULL COMMENT '浏览量',
  `summary` VARCHAR(50) NULL COMMENT '摘要',
  `content_url` TEXT(300) NULL COMMENT '内容的url',
  `course_collection_id` INT NOT NULL COMMENT '对应三级列表ID',
  PRIMARY KEY (`course_id`),
  INDEX `fk_course_info_user1_idx` (`author_id` ASC),
  INDEX `fk_course_info_course_collection1_idx` (`course_collection_id` ASC),
  CONSTRAINT `fk_course_info_course_collection1`
    FOREIGN KEY (`course_collection_id`)
    REFERENCES `mydb`.`course_collection` (`course_collection_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_info_user1`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`article_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article_type` (
  `article_id` INT UNSIGNED NOT NULL COMMENT '文章的主键',
  `type_name` VARCHAR(50) NULL COMMENT '类别名',
  PRIMARY KEY (`article_id`),
  CONSTRAINT `fk_article_type_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `mydb`.`article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`article_collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article_collection` (
  `article_id` INT UNSIGNED NOT NULL COMMENT '文章id',
  `user_id` INT NULL COMMENT '收藏用户的id',
  INDEX `fk_collect_article1_idx` (`article_id` ASC),
  CONSTRAINT `fk_collect_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `mydb`.`article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`article_top`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article_top` (
  `article_top_id` INT NOT NULL COMMENT '置顶表主键',
  `article_id` INT UNSIGNED NOT NULL COMMENT '文章表主键',
  `top_time` TIMESTAMP NULL COMMENT '置顶时间',
  PRIMARY KEY (`article_top_id`, `article_id`),
  INDEX `fk_top_article1_idx` (`article_id` ASC),
  CONSTRAINT `fk_top_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `mydb`.`article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_comment` (
  `course_comment_id` INT NOT NULL COMMENT '评论ID(主键)',
  `course_id` INT UNSIGNED NOT NULL COMMENT '教程ID',
  `user_id` INT UNSIGNED NOT NULL COMMENT '用户ID',
  `comment_time` TIMESTAMP NULL COMMENT '评论日期',
  `content` TEXT(500) NULL COMMENT '内容',
  PRIMARY KEY (`course_comment_id`),
  INDEX `fk_comment_user1_idx` (`user_id` ASC),
  INDEX `fk_comment_course_info1_idx` (`course_id` ASC),
  CONSTRAINT `fk_comment_course_info1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course_info` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_reply` (
  `course_reply_id` INT NOT NULL COMMENT '回复ID(主键)',
  `comment_id` INT NOT NULL COMMENT '评论ID',
  `reply_user_id` INT NULL COMMENT '用户id',
  `reply_time` TIMESTAMP NULL COMMENT '回复日期',
  `content` TEXT(500) NULL COMMENT '回复内容',
  PRIMARY KEY (`course_reply_id`),
  INDEX `fk_course_reply_comment1_idx` (`comment_id` ASC),
  CONSTRAINT `fk_course_reply_comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `mydb`.`course_comment` (`course_comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recommend_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recommend_course` (
  `course_id` INT UNSIGNED NOT NULL COMMENT '文章ID(主键)，外键当主键',
  `exectime` TIMESTAMP NULL COMMENT '操作日期(排序依据)',
  PRIMARY KEY (`course_id`),
  CONSTRAINT `fk_reco_course_course_info1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course_info` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`article_draft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article_draft` (
  `article_draft_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '文章表的ID',
  `user_id` INT UNSIGNED NULL COMMENT '	文章作者的用户名',
  `title` VARCHAR(50) NULL COMMENT '文章的标题\n',
  `create_time` TIMESTAMP NULL COMMENT '文章创建日期',
  `update_time` TIMESTAMP NULL COMMENT '最近更新时间',
  `content_url` TEXT(300) NULL COMMENT '文章内容url',
  `title_image_url` TEXT(300) NULL COMMENT '题图url',
  PRIMARY KEY (`article_draft_id`),
  INDEX `fk_user_article_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_article_user10`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_draft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_draft` (
  `course_draft_id` INT NOT NULL COMMENT '教程ID(主键)',
  `title` VARCHAR(45) NULL COMMENT '标题',
  `author_id` INT UNSIGNED NOT NULL COMMENT '作者',
  `createtime` TIMESTAMP NULL COMMENT '创建日期',
  `content_url` TEXT(300) NULL COMMENT '内容的url',
  PRIMARY KEY (`course_draft_id`),
  INDEX `fk_course_info_user1_idx` (`author_id` ASC),
  CONSTRAINT `fk_course_info_user10`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`slideshow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`slideshow` (
  `slideshow_id` INT NOT NULL COMMENT '轮播图表主键',
  `img_url` VARCHAR(200) NOT NULL COMMENT '图片路径',
  `seq` INT NOT NULL COMMENT '轮播图次序',
  `img_title` VARCHAR(20) NOT NULL COMMENT '图片标题',
  `target_url` VARCHAR(100) NOT NULL COMMENT '目的链接',
  PRIMARY KEY (`slideshow_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`board` (
  `board_id` INT NOT NULL COMMENT '版块表主键',
  `img_url` VARCHAR(60) NOT NULL COMMENT '版块图片路径',
  `board_url` VARCHAR(100) NOT NULL COMMENT '版块链接',
  `seq` INT NOT NULL COMMENT '板块次序',
  PRIMARY KEY (`board_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`qr_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`qr_code` (
  `qr_id` INT NOT NULL COMMENT '二维码表主键',
  `qr_code_url` VARCHAR(200) NULL COMMENT '二维码路径',
  `seq` INT NULL COMMENT '二维码次序',
  `qr_title` VARCHAR(10) NULL COMMENT '二维码标题',
  PRIMARY KEY (`qr_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
